
/*  FUNCIONES PARA FECHAS */

/* EXTRAER EL DIA DEL MES LA FECHA*/
SELECT DAYOFMONTH("2017-05-28");
SELECT DAYOFMONTH(NOW());

/* OBTENER EL NOMBRE DEL DIA DE LA FECHA*/
SELECT DAYNAME("2018-06-03");
SELECT DAYNAME(NOW());

/* OBTENER EL DÍA DE LA SEMANA DE LA FECHA*/
SELECT DAYOFWEEK("2018-11-01");
SELECT DAYOFWEEK(NOW());

/* OBTENER EL DÍA DEL AÑO DE LA FECHA*/
SELECT DAYOFYEAR("2018-11-01");
SELECT DAYOFYEAR(NOW());

/* OBTENER LA SEMANA DEL AÑO DE LA FECHA ACTUAL */
SELECT WEEK("2017-09-29");
SELECT WEEK(NOW());

/* EXTRAER EL MES DE LA FECHA*/
SELECT MONTH("2017-05-28");
SELECT MONTH(NOW());

/* OBTENER EL NOMBRE DEL MES DE LA FECHA*/
SELECT MONTHNAME("2018-06-03");
SELECT MONTHNAME(NOW());

/*OBTENER EL ULTIMO DIA DEL MES DE UNA FECHA*/
SELECT LAST_DAY("2017-09-12");
SELECT LAST_DAY(NOW());

/* EXTRAER EL AÑO DE LA FECHA*/
SELECT YEAR("2017-05-28");
SELECT YEAR(NOW());