
USE c_datos;

SELECT * FROM empleado;

/*EXTRAER EL DIA DEL MES*/
SELECT FECHA_CONTRATACION, DAYOFMONTH(FECHA_CONTRATACION) FROM EMPLEADO;

/*OBTENER EL NOMBRE DEL DIA EN QUE FUE CONTRATADO */
SELECT FECHA_CONTRATACION, DAYNAME(FECHA_CONTRATACION) FROM EMPLEADO;

/*OBTENER EL DÍA DE LA SEMANA */
SELECT FECHA_CONTRATACION, DAYOFWEEK(FECHA_CONTRATACION) FROM EMPLEADO;

/*OBTENER EL DIA DEL AÑO */
SELECT FECHA_CONTRATACION, DAYOFYEAR(FECHA_CONTRATACION) FROM EMPLEADO;

/*OBTENER LA SEMANA DEL AÑO */
SELECT FECHA_CONTRATACION, WEEK(FECHA_CONTRATACION) FROM EMPLEADO;

/*OBTENER EL MES EN QUE FUE CONTRATADO */
SELECT FECHA_CONTRATACION, MONTH(FECHA_CONTRATACION) FROM EMPLEADO;

/*OBTENER EL NOMBRE DEL MES*/
SELECT FECHA_CONTRATACION, MONTHNAME(FECHA_CONTRATACION) FROM EMPLEADO;

/*OBTENER EL AÑO*/
SELECT NOMBRE, FECHA_CONTRATACION, YEAR(FECHA_CONTRATACION) FROM EMPLEADO;