
/* FUNCIONES PARA HORAS */

SELECT CURRENT_TIME();

/*EXTRAER LA HORA DEL TIEMPO */
SELECT HOUR("10:30");
SELECT HOUR(CURRENT_TIME());

/* EXTRAER LOS MINUTOS DEL TIEMPO*/
SELECT MINUTE("10:30");
SELECT MINUTE(CURRENT_TIME());

/*EXTRAR LOS SEGUNDOS DEL TIEMPO*/
SELECT SECOND("10:30:25");
SELECT SECOND(CURRENT_TIME());

